spring:
  application:
    name: sungil-mealtracker
  datasource:
    url: jdbc:h2:file:./data/db;AUTO_SERVER=TRUE;
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8042

