-- CREATE USERS TABLE FOR TEACHERS AND ADMINISTRATORS
CREATE TABLE USERS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME   VARCHAR(50)  NOT NULL UNIQUE,
    PASSWORD   VARCHAR(100) NOT NULL,
    NAME       VARCHAR(100) NOT NULL,
    ROLE       VARCHAR(20)  NOT NULL, -- 'TEACHER' OR 'ADMIN'
    DEPARTMENT VARCHAR(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- CREATE MEAL RECORDS TABLE
CREATE TABLE MEAL_RECORDS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID    BIGINT  NOT NULL,
    MEAL_DATE  DATE    NOT NULL,
    IS_EATING  BOOLEAN NOT NULL DEFAULT FALSE,
    REASON     VARCHAR(255),
    CREATED_AT TIMESTAMP        DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP        DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
    UNIQUE (USER_ID, MEAL_DATE)
);

-- CREATE SETTINGS TABLE FOR APPLICATION CONFIGURATION
CREATE TABLE SETTINGS
(
    ID            BIGINT AUTO_INCREMENT PRIMARY KEY,
    SETTING_KEY   VARCHAR(50)  NOT NULL UNIQUE,
    SETTING_VALUE VARCHAR(255) NOT NULL,
    DESCRIPTION   VARCHAR(255),
    CREATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- INSERT DEFAULT ADMIN USER
INSERT INTO USERS (USERNAME, PASSWORD, NAME, ROLE, DEPARTMENT)
VALUES ('admin', '$2a$10$8.UnVuG9HHgffUDAlk8qfOuVGkqRzgVymGe07xd00DMxs.AQubh4a', '관리자', 'ADMIN', '관리부');

-- INSERT DEFAULT SETTINGS
INSERT INTO SETTINGS (SETTING_KEY, SETTING_VALUE, DESCRIPTION)
VALUES ('MEAL_CUTOFF_TIME', '09:00:00', '식사 신청 마감 시간'),
       ('SCHOOL_NAME', '성일정보고등학교', '학교 이름'),
       ('SCHOOL_LOGO_URL', '/images/logo.png', '학교 로고 URL');
